/**
 * DEFINE_SAMPLE_BANK(name, medium, cachePolicy)
 * DEFINE_SAMPLE_BANK_PTR(index, medium, cachePolicy)
 */
DEFINE_SAMPLE_BANK    (SampleBank_0, MEDIUM_CART, CACHE_LOAD_EITHER_NOSYNC)
DEFINE_SAMPLE_BANK_PTR(0, MEDIUM_CART, CACHE_LOAD_EITHER_NOSYNC)
DEFINE_SAMPLE_BANK    (SampleBank_2, MEDIUM_CART, CACHE_LOAD_EITHER_NOSYNC)
DEFINE_SAMPLE_BANK    (SampleBank_3, MEDIUM_CART, CACHE_LOAD_EITHER_NOSYNC)
DEFINE_SAMPLE_BANK    (SampleBank_4, MEDIUM_CART, CACHE_LOAD_EITHER_NOSYNC)
DEFINE_SAMPLE_BANK    (SampleBank_5, MEDIUM_CART, CACHE_LOAD_EITHER_NOSYNC)
DEFINE_SAMPLE_BANK    (SampleBank_6, MEDIUM_CART, CACHE_LOAD_EITHER_NOSYNC)
